=== chestersd/Task2_XML/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://epam.com/gems"
        xmlns:tns="http://epam.com/gems"
        elementFormDefault="qualified">

    <element name="gems">
        <complexType>
            <sequence>
                 <element ref="tns:gem"
                          minOccurs="2"
                          maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="gem">
        <sequence>
            <element name="id" type="positiveInteger"/>
            <element name="name" type="string"/>
            <element name="preciousness" type="tns:Preciousness"/>
        </sequence>
        <attribute name="preciousness" type="tns:Preciousness" use="optional"/>
    </complexType>

    <simpleType  name="Preciousness">
        <restriction base="string">
            <enumeration value="precious"/>
            <enumeration value="semiPrecious"/>
        </restriction>
    </simpleType >

    <complexType name="VisualParameters">
        <sequence>
            <element name="color" type="string"/>
            <element name="opacity" type="string"/>
            <element name="facets" type="positiveInteger"
                                    minOccurs="4"
                                    maxOccurs="15"/>
            <element name="weight" type="double"/>
        </sequence>
    </complexType>

    <complexType name="Synthesized">
        <complexContent>
            <extension base="tns:Synthesized"/>
        </complexContent>
    </complexType>

    <complexType name="Natural">
        <complexContent>
            <extension base="tns:Natural"/>
        </complexContent>
    </complexType>

    <element name="gem" type="tns:gem" abstract="true"/>
    <element name="Synthesized" type="tns:Synthesized" substitutionGroup="tns:gem"/>
    <element name="Natural" type="tns:Natural" substitutionGroup="tns:gem"/>
</schema>

=== chestersd/Task2_XML/fundTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.epam.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">

    <gem>
        <id>0</id>
        <name origin="SAR">brilliant</name>
        <preciousness>precious</preciousness>
        <natural>natural</natural>
        <visualParameters>
            <color>white</color>
            <opacity>98</opacity>
            <facets>15</facets>
            <weight>16</weight>
        </visualParameters>
    </gem>
    <gem>
        <id>1</id>
        <name origin="Russia">emerald</name>
        <preciousness>precious</preciousness>
        <natural>natural</natural>
        <visualParameters>
            <color>green</color>
            <opacity>42</opacity>
            <facets>12</facets>
            <weight>3</weight>
        </visualParameters>
    </gem>
    <gem>
        <id>2</id>
        <name origin="SAR">topaz</name>
        <preciousness>precious</preciousness>
        <visualParameters>
            <color>yellow</color>
            <opacity>76</opacity>
            <facets>14</facets>
            <weight>24</weight>
        </visualParameters>
    </gem>
    <gem>
        <id>3</id>
        <name factory="Nephrite manufacture">nephritis</name>
        <preciousness>semiPrecious</preciousness>
        <synthesized>synthesized</synthesized>
        <visualParameters>
            <color>black</color>
            <opacity>1</opacity>
            <facets>7</facets>
            <weight>14</weight>
        </visualParameters>
    </gem>
    <gem>
        <id>4</id>
        <name factory="Russkiye Samotsvety">cubic zirconia</name>
        <preciousness>semiPrecious</preciousness>
        <synthesized>synthesized</synthesized>
        <visualParameters>
            <color>white</color>
            <opacity>98</opacity>
            <facets>10</facets>
            <weight>5</weight>
        </visualParameters>
    </gem>
</gems>

=== chestersd/Task2_XML/fund.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.epam.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">

    <gem>
        <id>0</id>
        <name origin="SAR">brilliant</name>
        <preciousness>precious</preciousness>
        <visualParameters>
            <color>white</color>
            <opacity>98</opacity>
            <facets>15</facets>
            <weight>16</weight>
        </visualParameters>
    </gem>
    <gem>
        <id>1</id>
        <name origin="Russia">emerald</name>
        <preciousness>precious</preciousness>
        <visualParameters>
            <color>green</color>
            <opacity>42</opacity>
            <facets>12</facets>
            <weight>3</weight>
        </visualParameters>
    </gem>
    <gem>
    <id>2</id>
    <name origin="SAR">topaz</name>
    <preciousness>precious</preciousness>
    <visualParameters>
        <color>yellow</color>
        <opacity>76</opacity>
        <facets>14</facets>
        <weight>24</weight>
    </visualParameters>
    </gem>
    <gem>
        <id>3</id>
        <name factory="Nephrite manufacture">nephritis</name>
        <preciousness>semiPrecious</preciousness>
        <visualParameters>
            <color>black</color>
            <opacity>1</opacity>
            <facets>7</facets>
            <weight>14</weight>
        </visualParameters>
    </gem>
</gems>
